apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iot-p3-ingress
  namespace: dev
spec:
  ingressClassName: traefik
  rules:
  - host: deployed.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: iot-p3-playground-service
            port:
              number: 8888
