apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-p3-deployment
  namespace: dev
spec:
  replicas: 1
  selector: 
    matchLabels: 
     app: iot-p3-playground
  template:
    metadata:
      labels:
        app: iot-p3-playground
    spec:
      containers:
        - name: chrisap75-playground
          image: chrisap75/iot-p3:v1 
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: iot-p3-playground-service
  namespace: dev
spec:
  selector:
    app: iot-p3-playground
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888